### ISSUE TITLE
Android NDK crash

### ISSUE THREAD

**Issue by DenBond7** [eclipsesource/J2V8#432]
Hello. I have some problem with J2V8. It's an NDK error.

Maybe somebody knows what is wrong?

This error always kills my app.

```
2018-11-06 16:23:52.080 22263-23063/com.flowcrypt.email.debug A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xce400010 in tid 23063 (AsyncTask #8), pid 22263 (ypt.email.debug)
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:9/PSR1.180720.012/4923214:user/release-keys'
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: Revision: '0'
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: ABI: 'x86'
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: pid: 22263, tid: 23063, name: AsyncTask #8  >>> com.flowcrypt.email.debug <<<
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xce400010
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG:     eax ce400010  ebx d14d8c40  ecx 000ff43f  edx c5a0001e
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG:     edi c88deb80  esi 00000000
2018-11-06 16:23:52.169 23066-23066/? A/DEBUG:     ebp c8afc508  esp c8afc480  eip f08a344b
2018-11-06 16:23:52.328 23066-23066/? A/DEBUG: backtrace:
2018-11-06 16:23:52.328 23066-23066/? A/DEBUG:     #00 pc 0001b44b  /system/lib/libc.so (memmove+219)
2018-11-06 16:23:52.328 23066-23066/? A/DEBUG:     #01 pc 00847657  /data/app/com.flowcrypt.email.debug-Rs_7xEjB4zxNoxxmNiozCQ==/lib/x86/libj2v8.so (v8::internal::Runtime_TypedArraySetFastCases(int, v8::internal::Object**, v8::internal::Isolate*)+2023)
2018-11-06 16:23:52.328 23066-23066/? A/DEBUG:     #02 pc 0000007d  <anonymous:c0e0a000>
```

**Comment by tomholub** [comment]
I should add, we are seeing this error intermittently. Sometimes it will crash, sometimes it won't for the same op. Looks like a stability issue.

**Comment by tomholub** [comment]
@irbull Is there any way we can help you debug this?

**Comment by irbull** [comment]
There isn't much in that stack trace, but there is a bug with Typed Arrays and ArrayBuffers. If you were using this, it was possible to try to write to a ByteBuffer which had already been reclaimed and this would lead to a seg fault. Unfortunately, the fix is to remove access to the ByteBuffer since this is unsafe. I've been working on some new (safe) APIs in this space. 

I finally have builds working again, so I will be publishing some new J2V8 versions.

**Comment by irbull** [comment]
I've pushed a new version of 4.8 (`com.eclipsesource.j2v8:j2v8:4.8.3-SNAPSHOT@aar`) and the start of 5.x `com.eclipsesource.j2v8:j2v8:5.0.100-SNAPSHOT@aar`. Can you test and see if either of these help? They are both available from the snapshot repository. 
```
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
```

**Comment by DenBond7** [comment]
@irbull Thanks a lot for your reply. I've applied your changes but I'm still receiving errors like below.

Code (`'com.eclipsesource.j2v8:j2v8:4.8.2@aar'`)
```
private V8TypedArray uint8(byte[] data) {
    V8ArrayBuffer buffer = new V8ArrayBuffer(v8, new ArrayBuffer(data).getByteBuffer());
    return new V8TypedArray(v8, buffer, V8Value.UNSIGNED_INT_8_ARRAY, 0, data.length);
}
```

Code (`com.eclipsesource.j2v8:j2v8:4.8.3-SNAPSHOT@aar'`)

```
private V8TypedArray uint8(byte[] data) {
    ByteBuffer byteBuffer = ByteBuffer.allocateDirect(data.length);
    byteBuffer.put(data);
    V8ArrayBuffer buffer = new V8ArrayBuffer(v8, byteBuffer);
    return new V8TypedArray(v8, buffer, V8Value.UNSIGNED_INT_8_ARRAY, 0, data.length);
}
```
Error:
```
2019-01-20 16:59:17.273 3983-4756/com.flowcrypt.email.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe0d77010 in tid 4756 (AsyncTask #5)
2019-01-20 16:59:17.290 3432-3432/? D/KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
2019-01-20 16:59:17.293 3432-3432/? D/KeyguardUpdateMonitor: handleBatteryUpdate
2019-01-20 16:59:17.319 4773-4773/? W/crash_dump32: type=1400 audit(0.0:1233090): avc: denied { noatsecure } for scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:crash_dump:s0:c512,c768 tclass=process permissive=0
2019-01-20 16:59:17.537 4774-4774/? I/crash_dump32: obtaining output fd from tombstoned
2019-01-20 16:59:17.540 2186-2186/? I//system/bin/tombstoned: received crash request for pid 3983
2019-01-20 16:59:17.543 4774-4774/? I/crash_dump32: performing dump of process 3983 (target tid = 4756)
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: Build fingerprint: 'xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/V9.5.9.0.ODHMIFA:user/release-keys'
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: Revision: '0'
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: ABI: 'arm'
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: pid: 3983, tid: 4756, name: AsyncTask #5  >>> com.flowcrypt.email.debug <<<
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe0d77010
2019-01-20 16:59:17.544 4774-4774/? A/DEBUG:     r0 bd7e881d  r1 e0d77010  r2 0001348c  r3 00000003
2019-01-20 16:59:17.545 4774-4774/? A/DEBUG:     r4 c1aecc00  r5 c1ae5c00  r6 c34e0ff8  r7 c34e0074
2019-01-20 16:59:17.545 4774-4774/? A/DEBUG:     r8 bd7e8800  r9 00000000  sl 000134ac  fp cfcdd204
2019-01-20 16:59:17.545 4774-4774/? A/DEBUG:     ip 80000000  sp cfcdd1a0  lr d2ee9cd0  pc f135f164  cpsr a00d0010
2019-01-20 16:59:17.547 4774-4774/? A/DEBUG: backtrace:
2019-01-20 16:59:17.547 4774-4774/? A/DEBUG:     #00 pc 00019164  /system/lib/libc.so (memcpy+36)
2019-01-20 16:59:17.547 4774-4774/? A/DEBUG:     #01 pc 00726ccc  /data/app/com.flowcrypt.email.debug-EcpJH5yeXClfhB0CY217BQ==/lib/arm/libj2v8.so (_ZN2v88internal30Runtime_TypedArraySetFastCasesEiPPNS0_6ObjectEPNS0_7IsolateE+2204)
```

Code (`'com.eclipsesource.j2v8:j2v8:5.0.100-SNAPSHOT@aar'`)

```
private V8TypedArray uint8(byte[] data) {
    ByteBuffer byteBuffer = ByteBuffer.allocateDirect(data.length);
    byteBuffer.put(data);
    V8ArrayBuffer buffer = new V8ArrayBuffer(v8, byteBuffer);
    return new V8TypedArray(v8, buffer, V8Value.UNSIGNED_INT_8_ARRAY, 0, data.length);
}
```
Error:
```
2019-01-20 16:22:39.686 26156-26213/com.flowcrypt.email.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x11c66010 in tid 26213 (AsyncTask #2)
2019-01-20 16:22:39.889 28698-28698/? W/crash_dump32: type=1400 audit(0.0:1225626): avc: denied { noatsecure } for scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:crash_dump:s0:c512,c768 tclass=process permissive=0
2019-01-20 16:22:39.929 535-535/? W/memtrack@1.0-se: type=1400 audit(0.0:1225627): avc: denied { search } for name="proc" dev="debugfs" ino=13889 scontext=u:r:hal_memtrack_default:s0 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
2019-01-20 16:22:39.941 4479-6276/? E/SecUISvc: Error initializing local socket: -1
2019-01-20 16:22:40.019 28701-28701/? W/crash_dump32: type=1400 audit(0.0:1225629): avc: denied { search } for name="com.flowcrypt.email.debug" dev="dm-0" ino=745839 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
2019-01-20 16:22:40.070 28701-28701/? I/crash_dump32: obtaining output fd from tombstoned
2019-01-20 16:22:40.070 2186-2186/? I//system/bin/tombstoned: received crash request for pid 26156
2019-01-20 16:22:40.073 28701-28701/? I/crash_dump32: performing dump of process 26156 (target tid = 26213)
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: Build fingerprint: 'xiaomi/tissot/tissot_sprout:8.0.0/OPR1.170623.026/V9.5.9.0.ODHMIFA:user/release-keys'
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: Revision: '0'
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: ABI: 'arm'
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: pid: 26156, tid: 26213, name: AsyncTask #2  >>> com.flowcrypt.email.debug <<<
2019-01-20 16:22:40.073 28701-28701/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x11c66010
2019-01-20 16:22:40.074 28701-28701/? A/DEBUG:     r0 a6200023  r1 11c66010  r2 002c8cd2  r3 0000000d
2019-01-20 16:22:40.074 28701-28701/? A/DEBUG:     r4 c14dd300  r5 c14d6300  r6 9d27bff8  r7 9d27b074
2019-01-20 16:22:40.074 28701-28701/? A/DEBUG:     r8 a6200000  r9 00000000  sl 002c8d02  fp c2dfd204
2019-01-20 16:22:40.074 28701-28701/? A/DEBUG:     ip 80000000  sp c2dfd1a0  lr d2eeae50  pc f135f164  cpsr 800d0010
2019-01-20 16:22:40.078 28701-28701/? A/DEBUG: backtrace:
2019-01-20 16:22:40.078 28701-28701/? A/DEBUG:     #00 pc 00019164  /system/lib/libc.so (memcpy+36)
2019-01-20 16:22:40.078 28701-28701/? A/DEBUG:     #01 pc 00726e4c  /data/app/com.flowcrypt.email.debug-6BqC97iZssEWl4LoS6jZKQ==/lib/arm/libj2v8.so (_ZN2v88internal30Runtime_TypedArraySetFastCasesEiPPNS0_6ObjectEPNS0_7IsolateE+2204)
```
